/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petshop;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

/**
 *
 * @author Isaac
 */
public class AdminConsole extends javax.swing.JFrame {

    /**
     * Creates new form AdminConsole
     */
    public AdminConsole() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Output = new javax.swing.JTextArea();
        ClearBox = new javax.swing.JButton();
        LogContents = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 2, 48)); // NOI18N
        jLabel1.setText("Admin Console");

        Output.setEditable(false);
        Output.setColumns(20);
        Output.setRows(5);
        jScrollPane1.setViewportView(Output);

        ClearBox.setText("ClearBox");
        ClearBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBoxActionPerformed(evt);
            }
        });

        LogContents.setText("Get Log Contents");
        LogContents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogContentsActionPerformed(evt);
            }
        });

        jButton1.setText("Change stock");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Log Out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 516, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LogContents)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ClearBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LogContents)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ClearBox)
                            .addComponent(jButton2))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClearBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBoxActionPerformed
        // TODO add your handling code here:
        Output.setText(null);
    }//GEN-LAST:event_ClearBoxActionPerformed

    private void LogContentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogContentsActionPerformed
        // TODO add your handling code here:
        Output.setText(null);
        String newline = "\n";
        File dirl = new File("res/log.txt");
        Scanner read = null;
        try{
             read = new Scanner(dirl);
        }catch(FileNotFoundException e){
            System.out.println("File Not Found");
        }
        while(read.hasNext()){
            Output.append(read.next() + newline + newline);
            
        }
        
    }//GEN-LAST:event_LogContentsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Output.setText(null);
        String newline = "\n";
        File dirl = new File("res/Stock.txt");
        Scanner read = null;
        try{
            read = new Scanner(dirl);
        }catch(FileNotFoundException e ){
            e.printStackTrace();
        }
        String str = (String) read.next();
        int Cat =  Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int Dog = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int Fish = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int Rabbit = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int ToyBone = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int FakeMouse = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int Brush = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int ThrowingBall = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int CatFood = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int DogFood  = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int FishFood = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int RabbitFood = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        
        Output.append("Current Stock: "+ newline);
        Output.append("Cats: "+ Cat + newline);
        Output.append("Dogs: "+ Dog + newline);
        Output.append("Fish: "+ Fish + newline);
        Output.append("Rabbits: "+ Rabbit + newline + newline);
        Output.append("ToyBones: "+ ToyBone + newline);
        Output.append("FakeMice: "+ FakeMouse + newline);
        Output.append("Brushes: "+ Brush + newline);
        Output.append("Balls: "+ ThrowingBall + newline + newline);
        Output.append("CatFood: "+ CatFood + newline);
        Output.append("DogFood: "+ DogFood + newline);
        Output.append("FishFood: "+ FishFood + newline);
        Output.append("RabbitFood: "+ RabbitFood + newline);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Welcome_Menu login = new Welcome_Menu();
        setVisible(false);
        this.dispose();
        login.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminConsole().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearBox;
    private javax.swing.JButton LogContents;
    private javax.swing.JTextArea Output;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
