/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petshop;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Isaac
 */
public class ChangeStock extends javax.swing.JFrame {

    /**
     * Creates new form ChangeStock
     */
    public ChangeStock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        toybone = new javax.swing.JSpinner();
        fakemouse = new javax.swing.JSpinner();
        brushes = new javax.swing.JSpinner();
        tballs = new javax.swing.JSpinner();
        catfood = new javax.swing.JSpinner();
        dogfood = new javax.swing.JSpinner();
        fishfood = new javax.swing.JSpinner();
        rabbitfood = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        AddCat = new javax.swing.JButton();
        AddDog = new javax.swing.JButton();
        AddRabbit = new javax.swing.JButton();
        AddFish = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Animals:");

        jLabel2.setText("Cats:");

        jLabel3.setText("Dogs:");

        jLabel4.setText("Fish:");

        jLabel5.setText("Rabbits:");

        jLabel6.setText("Toys:");

        jLabel7.setText("ToyBone:");

        jLabel8.setText("FakeMouse:");

        jLabel9.setText("Brushes:");

        jLabel10.setText("ThrowingBalls:");

        jLabel11.setText("Food:");

        jLabel12.setText("CatFood:");

        jLabel13.setText("DogFood:");

        jLabel14.setText("FishFood:");

        jLabel15.setText("RabbitFood:");

        toybone.setModel(new javax.swing.SpinnerNumberModel(0, 0, 40, 1));

        fakemouse.setModel(new javax.swing.SpinnerNumberModel(0, 0, 40, 1));

        brushes.setModel(new javax.swing.SpinnerNumberModel(0, 0, 40, 1));

        tballs.setModel(new javax.swing.SpinnerNumberModel(0, 0, 40, 1));

        catfood.setModel(new javax.swing.SpinnerNumberModel(0, 0, 40, 1));

        dogfood.setModel(new javax.swing.SpinnerNumberModel(0, 0, 40, 1));

        fishfood.setModel(new javax.swing.SpinnerNumberModel(0, 0, 40, 1));

        rabbitfood.setModel(new javax.swing.SpinnerNumberModel(0, 0, 40, 1));

        jLabel16.setText("What would you like to add to the stock?");

        add.setText("Add Items");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        AddCat.setText("Add");
        AddCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCatActionPerformed(evt);
            }
        });

        AddDog.setText("Add");
        AddDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDogActionPerformed(evt);
            }
        });

        AddRabbit.setText("Add");
        AddRabbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRabbitActionPerformed(evt);
            }
        });

        AddFish.setText("Add");
        AddFish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFishActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Cancel");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(catfood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dogfood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fishfood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rabbitfood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toybone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddCat)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddDog))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fakemouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddFish)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddRabbit))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(brushes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tballs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel11)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(AddCat)
                    .addComponent(AddDog)
                    .addComponent(AddRabbit)
                    .addComponent(AddFish))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(toybone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fakemouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brushes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tballs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(catfood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dogfood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fishfood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rabbitfood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        
        int tboneAmount = (Integer) toybone.getValue();
        int fmouseAmount = (Integer) fakemouse.getValue();
        int brushAmount = (Integer) brushes.getValue();
        int ballAmount = (Integer) tballs.getValue();
        int catfAmount = (Integer) catfood.getValue();
        int dogfAmount = (Integer) dogfood.getValue();
        int fishfAmount = (Integer) fishfood.getValue();
        int rabbitfAmount = (Integer) rabbitfood.getValue();
        
        File dirl2 = new File("res/Stock.txt");
        Scanner read = null;
        try{
            read = new Scanner(dirl2);
        }catch(FileNotFoundException e ){
            e.printStackTrace();
        }
        String str = (String) read.next();
        int Cat =  Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int Dog = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int Fish = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int Rabbit = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int ToyBone = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int FakeMouse = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int Brush = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int ThrowingBall = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int CatFood = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int DogFood  = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int FishFood = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int RabbitFood = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        ToyBone+=tboneAmount;
        FakeMouse+=fmouseAmount;
        Brush+=brushAmount;
        ThrowingBall+=ballAmount;
        CatFood+=catfAmount;
        DogFood+=dogfAmount;
        FishFood+=fishfAmount;
        RabbitFood+=rabbitfAmount;
        String Cat1 = Integer.toString(Cat);
        if(Cat < 10){
            Cat1 = "0"+Cat;
        }
        String Dog1 = Integer.toString(Dog);
        if(Dog < 10){
            Dog1 = "0"+Dog;
        }
        String Fish1 = Integer.toString(Fish);
        if(Fish < 10){
            Fish1 = "0"+Fish;
        }
        String Rab1 = Integer.toString(Rabbit);
        if(Rabbit < 10){
            Rab1 = "0"+Rabbit;
        }
        String tbone = Integer.toString(ToyBone);
        if(ToyBone < 10){
            tbone = "0"+ToyBone;
        }
        String fmouse = Integer.toString(FakeMouse);
        if(FakeMouse < 10){
            fmouse = "0"+FakeMouse;
        }
        String brush = Integer.toString(Brush);
        if(Brush < 10){
            brush = "0"+Brush;
        }
        String ball = Integer.toString(ThrowingBall);
        if(ThrowingBall < 10){
            ball = "0"+ThrowingBall;
        }
        String catf = Integer.toString(CatFood);
        if(CatFood < 10){
            catf = "0"+CatFood;
        }
        String dogf = Integer.toString(DogFood);
        if(DogFood < 10){
            dogf = "0"+DogFood;
        }
        String fishf = Integer.toString(FishFood);
        if(FishFood < 10){
            fishf = "0"+FishFood;
        }
        String rabf = Integer.toString(RabbitFood);
        if(RabbitFood < 10){
            rabf = "0"+RabbitFood;
        }

        File dirl3 = new File("res/Stock.txt");
            try{
                 BufferedWriter out = new BufferedWriter(new FileWriter(dirl3,false));
                 out.write("Cat_" + Cat1);
                 out.newLine();
                 out.write("Dog_" + Dog1);
                 out.newLine();
                 out.write("Fish_" + Fish1);
                 out.newLine();
                 out.write("Rabbit_" + Rab1);
                 out.newLine();
                 out.write("ToyBone_" + tbone);
                 out.newLine();
                 out.write("FakeMouse_" + fmouse);
                 out.newLine();
                 out.write("Brush_" + brush);
                 out.newLine();
                 out.write("ThrowingBall_" + ball);
                 out.newLine();
                 out.write("CatFood_" + catf);
                 out.newLine();
                 out.write("DogFood_" + dogf);
                 out.newLine();
                 out.write("FishFood_" + fishf);
                 out.newLine();
                 out.write("RabbitFood_" + rabf);
                 out.newLine();
                 out.close();
            }catch(FileNotFoundException e){
                e.printStackTrace();
            } catch (IOException ex) {
                Logger.getLogger(Shop.class.getName()).log(Level.SEVERE, null, ex);
            }
        
            
        JOptionPane.showMessageDialog(null, "Items have been added!");
        setVisible(false);
        this.dispose();
        AdminConsole admin = new AdminConsole ();
        
            
    }//GEN-LAST:event_addActionPerformed

    private void AddCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCatActionPerformed
        // TODO add your handling code here:
        AddCat cat = new AddCat();
        cat.show();
        
    }//GEN-LAST:event_AddCatActionPerformed

    private void AddDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDogActionPerformed
        // TODO add your handling code here:

        AddDog dog = new AddDog();
        dog.show();
    }//GEN-LAST:event_AddDogActionPerformed

    private void AddRabbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRabbitActionPerformed
        // TODO add your handling code here:
        AddRabbit rabbit = new AddRabbit();
        rabbit.show();
    }//GEN-LAST:event_AddRabbitActionPerformed

    private void AddFishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFishActionPerformed
        // TODO add your handling code here:
        AddFish fish = new AddFish();
        fish.show();
        
        
        
    }//GEN-LAST:event_AddFishActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCat;
    private javax.swing.JButton AddDog;
    private javax.swing.JButton AddFish;
    private javax.swing.JButton AddRabbit;
    private javax.swing.JButton add;
    private javax.swing.JSpinner brushes;
    private javax.swing.JSpinner catfood;
    private javax.swing.JSpinner dogfood;
    private javax.swing.JSpinner fakemouse;
    private javax.swing.JSpinner fishfood;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JSpinner rabbitfood;
    private javax.swing.JSpinner tballs;
    private javax.swing.JSpinner toybone;
    // End of variables declaration//GEN-END:variables
}
