/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petshop;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.Timer;

/**
 *
 * @author Isaac
 */
public class Shop extends javax.swing.JFrame {

    
    
    String username;
    
    
    
    public void setUser(String user){
        this.username = user;
        jLabel2.setText("Welcome: "+username);
        ClockPane();
        getMaxStock();
    }
    public void disableButtons(String animal){
        adoptCat.setEnabled(false);
        adoptDog.setEnabled(false);
        adoptRabbit.setEnabled(false);
        adoptFish.setEnabled(false);
        
        if(animal.equals("cat")){
            catAmount++;
        }else if(animal.equals("dog")){
            dogAmount++;
        }else if(animal.equals("fish")){
            fishAmount++;
        }else if(animal.equals("rabbit")){
            rabbitAmount++;
        }
    }
    /**
     * Creates new form Shop
     */
    public Shop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        CatComboBox2 = new javax.swing.JComboBox<>();
        DogComboBox2 = new javax.swing.JComboBox<>();
        FIshComboBox2 = new javax.swing.JComboBox<>();
        RabbitComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Amount = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        CatSpinner = new javax.swing.JSpinner();
        DogSpinner = new javax.swing.JSpinner();
        FishSpinner = new javax.swing.JSpinner();
        RabbitSpinner = new javax.swing.JSpinner();
        clock = new javax.swing.JLabel();
        ToyBoneSpinner = new javax.swing.JSpinner();
        FakeMouseSpinner = new javax.swing.JSpinner();
        BrushSpinner = new javax.swing.JSpinner();
        BallSpinner = new javax.swing.JSpinner();
        CatFoodSpinner = new javax.swing.JSpinner();
        DogFoodSpinner = new javax.swing.JSpinner();
        FishFoodSpinner = new javax.swing.JSpinner();
        RabbitFoodSpinner = new javax.swing.JSpinner();
        BuyNow = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        adoptCat = new javax.swing.JToggleButton();
        adoptDog = new javax.swing.JToggleButton();
        adoptFish = new javax.swing.JToggleButton();
        adoptRabbit = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel16.setText("Cat");

        jLabel17.setText("Dog");

        jLabel18.setText("Fish");

        jLabel19.setText("Rabbit");

        CatComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", " " }));
        CatComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatComboBox2ActionPerformed(evt);
            }
        });

        DogComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", " " }));
        DogComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DogComboBox2ActionPerformed(evt);
            }
        });

        FIshComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", " " }));
        FIshComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIshComboBox2ActionPerformed(evt);
            }
        });

        RabbitComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", " " }));
        RabbitComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RabbitComboBox2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel1.setText("What would you like to buy?");

        jLabel2.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel2.setText("Welcome: User");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Animals:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("Toys:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("Food:");

        jLabel6.setText("Total:    £");

        Amount.setText("__");

        jButton1.setText("Calculate Amount");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Cat: £50");

        jLabel9.setText("Dog: £300");

        jLabel10.setText("Fish: £10");

        jLabel11.setText("Rabbit: £35");

        jLabel12.setText("Toy Bone: £5");

        jLabel13.setText("Fake Mouse: £3");

        jLabel14.setText("Brush: £5");

        jLabel15.setText("Throwing Balls: £6");

        jLabel20.setText("Cat Food: £10");

        jLabel21.setText("Dog Food: £15");

        jLabel22.setText("Fish Food: £7");

        jLabel23.setText("Rabbit Food: £10");

        CatSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        DogSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        FishSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        RabbitSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        clock.setText("(Date and Time)");

        ToyBoneSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        FakeMouseSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        BrushSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        BallSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        CatFoodSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));

        DogFoodSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));

        FishFoodSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));

        RabbitFoodSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));

        BuyNow.setText("Buy now");
        BuyNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyNowActionPerformed(evt);
            }
        });

        jButton4.setText("Log Out");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        adoptCat.setText("Adopt");
        adoptCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adoptCatActionPerformed(evt);
            }
        });

        adoptDog.setText("Adopt");
        adoptDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adoptDogActionPerformed(evt);
            }
        });

        adoptFish.setText("Adopt");

        adoptRabbit.setText("Adopt");
        adoptRabbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adoptRabbitActionPerformed(evt);
            }
        });

        jLabel7.setText("(you can only adopt one animal at a time)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(57, 57, 57)
                                            .addComponent(BuyNow)
                                            .addGap(15, 15, 15))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel6)
                                            .addGap(20, 20, 20)
                                            .addComponent(Amount)
                                            .addGap(48, 48, 48))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(27, 27, 27)
                                                        .addComponent(CatFoodSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(47, 47, 47)
                                                        .addComponent(DogFoodSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(33, 33, Short.MAX_VALUE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel20)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel21)
                                                        .addGap(18, 18, 18)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel22)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(FishFoodSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(36, 36, 36)
                                                        .addComponent(jLabel23))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(37, 37, 37)
                                                        .addComponent(RabbitFoodSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addContainerGap())))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel4)
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel12)
                                                    .addComponent(ToyBoneSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(56, 56, 56)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel13)
                                                    .addComponent(FakeMouseSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(53, 53, 53)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel14)
                                                    .addComponent(BrushSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(43, 43, 43)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(BallSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabel15)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8)
                                                    .addComponent(CatSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(adoptCat)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(DogSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(adoptDog)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(FishSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(adoptFish)))
                                                .addGap(2, 2, 2)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(RabbitSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(adoptRabbit)))))
                                        .addGap(26, 26, 26))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(clock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CatSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DogSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FishSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RabbitSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adoptCat)
                    .addComponent(adoptDog)
                    .addComponent(adoptFish)
                    .addComponent(adoptRabbit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ToyBoneSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FakeMouseSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BrushSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BallSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(jLabel23)
                        .addComponent(jLabel21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CatFoodSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FishFoodSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RabbitFoodSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(Amount))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BuyNow))))
                    .addComponent(DogFoodSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CatComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CatComboBox2ActionPerformed

    private void DogComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DogComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DogComboBox2ActionPerformed

    private void FIshComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIshComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FIshComboBox2ActionPerformed

    private void RabbitComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RabbitComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RabbitComboBox2ActionPerformed
    private int catAmount = 0;
    private int dogAmount = 0;
    private int fishAmount = 0;
    private int rabbitAmount = 0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int tboneAmount = (Integer) ToyBoneSpinner.getValue();
        int fmouseAmount = (Integer) FakeMouseSpinner.getValue();
        int brushAmount = (Integer) BrushSpinner.getValue();
        int ballAmount = (Integer) BallSpinner.getValue();
        int catfAmount = (Integer) CatFoodSpinner.getValue();
        int dogfAmount = (Integer) DogFoodSpinner.getValue();
        int fishfAmount = (Integer) FishFoodSpinner.getValue();
        int rabbitfAmount = (Integer) RabbitFoodSpinner.getValue();
        
        
        
        int TotalMoney = (catAmount * 50) + (dogAmount * 300) + (fishAmount * 10) + (rabbitAmount * 35) +
                        (tboneAmount * 5) + (fmouseAmount * 3) + (brushAmount * 5) + (ballAmount * 6) +
                        (catfAmount * 10) + (dogfAmount * 15) + (fishfAmount * 7) + (rabbitfAmount * 10);
        Amount.setText(Integer.toString(TotalMoney));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BuyNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyNowActionPerformed
        // TODO add your handling code here:
        int catAmount = (Integer) CatSpinner.getValue();
        int dogAmount = (Integer) DogSpinner.getValue();
        int fishAmount = (Integer) FishSpinner.getValue();
        int rabbitAmount = (Integer) RabbitSpinner.getValue();
        int tboneAmount = (Integer) ToyBoneSpinner.getValue();
        int fmouseAmount = (Integer) FakeMouseSpinner.getValue();
        int brushAmount = (Integer) BrushSpinner.getValue();
        int ballAmount = (Integer) BallSpinner.getValue();
        int catfAmount = (Integer) CatFoodSpinner.getValue();
        int dogfAmount = (Integer) DogFoodSpinner.getValue();
        int fishfAmount = (Integer) FishFoodSpinner.getValue();
        int rabbitfAmount = (Integer) RabbitFoodSpinner.getValue();
        
        
        String amount = Amount.getText();
        if("__".equals(amount)){
            JOptionPane.showMessageDialog(null, "You need to calculate total amount first");
        }else if("0".equals(amount)){
            JOptionPane.showMessageDialog(null, "There's nothing in your basket");
        }else{
            System.out.println("Your total was "+Amount.getText());
            
            File dirl = new File("res/log.txt");
            
            String time = DateFormat.getDateTimeInstance().format(new Date());
            StringBuilder bought = new StringBuilder();
            if( catAmount != 0){
                bought.append("_Cat:").append(catAmount);
            }
            if( dogAmount != 0){
                bought.append("_Dog:").append(dogAmount);
            }
            if( fishAmount != 0){
                bought.append("_Fish:").append(fishAmount);
            }
            if( rabbitAmount != 0){
                bought.append("_Rabbit:").append(rabbitAmount);
            }
            if( tboneAmount != 0){
                bought.append("_ToyBone:").append(tboneAmount);
            }
            if( fmouseAmount != 0){
                bought.append("_FakeMouse:").append(fmouseAmount);
            }
            if( brushAmount != 0){
                bought.append("_Brush:").append(brushAmount);
            }
            if( ballAmount != 0){
                bought.append("_ThrowingBall:").append(dogAmount);
            }
            if( catfAmount != 0){
                bought.append("_CatFood:").append(catfAmount);
            }
            if( dogfAmount != 0){
                bought.append("_DogFood:").append(dogfAmount);
            }
            if( fishfAmount != 0){
                bought.append("_FishFood:").append(fishfAmount);
            }
            if( rabbitfAmount != 0){
                bought.append("_RabbitFood:").append(rabbitfAmount);
            }       
            int total = Integer.parseInt(Amount.getText());
            try{
                BufferedWriter out = new BufferedWriter(new FileWriter(dirl,true));
                out.newLine();
                out.write("Customer_"+username +" Date_"+time+" Items_" + bought +" Total_£"+total);
                out.close();
            } catch(FileNotFoundException e ){
                e.printStackTrace();
            } catch (IOException ex) {
                Logger.getLogger(Shop.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, (username + ", you have succeffully bought these items"));
            setAllZero();
            Amount.setText("__");
            
            
            
            ChangeFiles change = new ChangeFiles();
            change.ChangeStock(0, 0, 0, 0, -tboneAmount, -fmouseAmount, -brushAmount, -ballAmount, -catfAmount, -dogfAmount, -fishfAmount, -rabbitfAmount);
            
            getMaxStock();
            
        }
    }//GEN-LAST:event_BuyNowActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Welcome_Menu login = new Welcome_Menu();
        setVisible(false);
        this.dispose();
        login.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void adoptCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adoptCatActionPerformed
        // TODO add your handling code here:
        
        
        Adopt adopt = new Adopt();
        setVisible(false);
        this.dispose();
        adopt.setAnimal("cat",username);
        adopt.show();
    }//GEN-LAST:event_adoptCatActionPerformed

    private void adoptDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adoptDogActionPerformed
        // TODO add your handling code here:
        Adopt adopt = new Adopt();
        setVisible(false);
        this.dispose();
        adopt.setAnimal("dog",username);
        adopt.show();
    }//GEN-LAST:event_adoptDogActionPerformed

    private void adoptRabbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adoptRabbitActionPerformed
        // TODO add your handling code here:
        Adopt adopt = new Adopt();
        setVisible(false);
        this.dispose();
        adopt.setAnimal("rabbit",username);
        adopt.show();
        
    }//GEN-LAST:event_adoptRabbitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Shop shop = new Shop();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shop().setVisible(true);
            }
        });
        
    }

    public void ClockPane() {
        tickTock();
        add(clock);
        Timer timer = new Timer(500, (ActionEvent e) -> {
            tickTock();
        });
        timer.setRepeats(true);
        timer.setCoalesce(true);
        timer.setInitialDelay(0);
        timer.start();
  }
    public void tickTock() {
        clock.setText(DateFormat.getDateTimeInstance().format(new Date()));
    
  }

    public void setAllZero(){
        CatSpinner.setValue(0);
        DogSpinner.setValue(0);
        FishSpinner.setValue(0);
        RabbitSpinner.setValue(0);
        ToyBoneSpinner.setValue(0);
        FakeMouseSpinner.setValue(0);
        BrushSpinner.setValue(0);
        BallSpinner.setValue(0);
        CatFoodSpinner.setValue(0);
        DogFoodSpinner.setValue(0);
        FishFoodSpinner.setValue(0);
        RabbitFoodSpinner.setValue(0);
    }
    
    public void getMaxStock(){
        File dirl = new File("res/Stock.txt");
        Scanner read = null;
        try{
            read = new Scanner(dirl);
        }catch(FileNotFoundException e ){
            e.printStackTrace();
        }
        String str = (String) read.next();
        int Cat =  Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int Dog = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int Fish = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int Rabbit = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int ToyBone = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int FakeMouse = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int Brush = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int ThrowingBall = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int CatFood = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int DogFood  = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int FishFood = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        str = (String) read.next();
        int RabbitFood = Integer.parseInt(str.length() > 2 ? str.substring(str.length() - 2) : str);
        
        SpinnerNumberModel model = (SpinnerNumberModel) CatSpinner.getModel();
        CatSpinner.setValue(0);
        model.setMaximum(Cat);
        
        SpinnerNumberModel modeldog = (SpinnerNumberModel) DogSpinner.getModel();
        DogSpinner.setValue(0);
        modeldog.setMaximum(Dog);
        
        SpinnerNumberModel modelfish = (SpinnerNumberModel) FishSpinner.getModel();
        FishSpinner.setValue(0);
        modelfish.setMaximum(Fish);
        
        SpinnerNumberModel modelrabbit = (SpinnerNumberModel) RabbitSpinner.getModel();
        RabbitSpinner.setValue(0);
        modelrabbit.setMaximum(Rabbit);
        
        SpinnerNumberModel modeltoybone = (SpinnerNumberModel) ToyBoneSpinner.getModel();
        ToyBoneSpinner.setValue(0);
        modeltoybone.setMaximum(ToyBone);
        
        SpinnerNumberModel modelfakemouse = (SpinnerNumberModel) FakeMouseSpinner.getModel();
        FakeMouseSpinner.setValue(0);
        modelfakemouse.setMaximum(FakeMouse);
        
        SpinnerNumberModel modelbrush = (SpinnerNumberModel) BrushSpinner.getModel();
        BrushSpinner.setValue(0);
        modelbrush.setMaximum(Brush);
        
        SpinnerNumberModel modelthrowing = (SpinnerNumberModel) BallSpinner.getModel();
        BallSpinner.setValue(0);
        modelthrowing.setMaximum(ThrowingBall);
        
        SpinnerNumberModel modelcatfood = (SpinnerNumberModel) CatFoodSpinner.getModel();
        CatFoodSpinner.setValue(0);
        modelcatfood.setMaximum(CatFood);
        
        SpinnerNumberModel modeldogfood = (SpinnerNumberModel) DogFoodSpinner.getModel();
        DogFoodSpinner.setValue(0);
        modeldogfood.setMaximum(DogFood);
        
        SpinnerNumberModel modelfishfood = (SpinnerNumberModel) FishFoodSpinner.getModel();
        FishFoodSpinner.setValue(0);
        modelfishfood.setMaximum(FishFood);
        
        SpinnerNumberModel modelrabbitfood = (SpinnerNumberModel) RabbitFoodSpinner.getModel();
        RabbitFoodSpinner.setValue(0);
        modelrabbitfood.setMaximum(RabbitFood);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Amount;
    private javax.swing.JSpinner BallSpinner;
    private javax.swing.JSpinner BrushSpinner;
    private javax.swing.JButton BuyNow;
    private javax.swing.JComboBox<String> CatComboBox2;
    private javax.swing.JSpinner CatFoodSpinner;
    private javax.swing.JSpinner CatSpinner;
    private javax.swing.JComboBox<String> DogComboBox2;
    private javax.swing.JSpinner DogFoodSpinner;
    private javax.swing.JSpinner DogSpinner;
    private javax.swing.JComboBox<String> FIshComboBox2;
    private javax.swing.JSpinner FakeMouseSpinner;
    private javax.swing.JSpinner FishFoodSpinner;
    private javax.swing.JSpinner FishSpinner;
    private javax.swing.JComboBox<String> RabbitComboBox2;
    private javax.swing.JSpinner RabbitFoodSpinner;
    private javax.swing.JSpinner RabbitSpinner;
    private javax.swing.JSpinner ToyBoneSpinner;
    private javax.swing.JToggleButton adoptCat;
    private javax.swing.JToggleButton adoptDog;
    private javax.swing.JToggleButton adoptFish;
    private javax.swing.JToggleButton adoptRabbit;
    private javax.swing.JLabel clock;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables

   


}
